Repository eclipse-rap/org.eclipse.rap, pull requests merged in 2022-07, with the labels that each got.

#31 Fix an issue with year picked from the calendar below 1970
  bundles/org.eclipse.rap.rwt/js/rwt/widgets/DateTimeDate.js
Labels: bug

#32 Add support for MenuItem tooltip text
  bundles/org.eclipse.rap.rwt/js/rwt/remote/handler/MenuItemHandler.js
  bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/MenuItem.java
  bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/widgets/menuitemkit/MenuItemLCA.java
  examples/org.eclipse.rap.demo.controls/src/org/eclipse/rap/demo/controls/ShellTab.java
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/internal/widgets/menuitemkit/MenuItemLCA_Test.java
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/widgets/MenuItem_Test.java
Labels: enhancement

#34 Update build configuration for RAP Runtime 3.22.0 M1
  bundles/org.eclipse.e4.ui.workbench.swt/META-INF/MANIFEST.MF
  bundles/org.eclipse.e4.ui.workbench/META-INF/MANIFEST.MF
  bundles/org.eclipse.rap.rwt.osgi/META-INF/MANIFEST.MF
  features/org.eclipse.rap.e4.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.sdk.feature/.forceQualifierUpdate
  features/org.eclipse.rap.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.feature/.forceQualifierUpdate
  features/org.eclipse.rap.sdk.feature/.forceQualifierUpdate
  releng/org.eclipse.rap.build/pom.xml
Labels: releng

#35 Add possibility to disable shutdown request
  bundles/org.eclipse.rap.rwt/js/rwt/remote/handler/DisplayHandler.js
  bundles/org.eclipse.rap.rwt/js/rwt/widgets/Display.js
  bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/client/WebClient.java
  bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/widgets/displaykit/DisplayLCA.java
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/internal/widgets/displaykit/DisplayLCA_Test.java
Labels: enhancement

#36 Fix e4 part stack styling and activation
  bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java
  bundles/org.eclipse.e4.ui.workbench.swt/.classpath
  bundles/org.eclipse.e4.ui.workbench.swt/build.properties
  bundles/org.eclipse.e4.ui.workbench.swt/src-rap/org/eclipse/e4/ui/internal/workbench/swt/StylingEngineImpl.java
  bundles/org.eclipse.e4.ui.workbench.swt/src/org/eclipse/e4/ui/internal/workbench/swt/E4Application.java
Labels: enhancement

#37 Include new OSGi package dependencies in Equinox features
  features/org.eclipse.rap.e4.equinox.target.feature/feature.xml
  features/org.eclipse.rap.equinox.target.feature/feature.xml
Labels: releng

#38 Fix remaining dependency issues by adding more OSGi service bundles
  features/org.eclipse.rap.e4.equinox.target.feature/feature.xml
  features/org.eclipse.rap.equinox.target.feature/feature.xml
Labels: releng
