Repository eclipse-rap/org.eclipse.rap, pull requests merged in 2022-11, with the labels that each got.

#77 Fix encoding problems with resource bundles encoded in UTF-8
  bundles/org.eclipse.rap.rwt/.settings/.api_filters
  bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/RWT.java
  bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/Utf8ResourceBundle.java
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/NLS_Test.java
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/incomplete_messages.properties
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/messages.properties
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/messages_de.properties
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/messages_it.properties
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/messages_utf8.properties
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/messages_utf8_de.properties
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/messages_utf8_it.properties
Labels: bug, enhancement

#79 Update build configuration for RAP Runtime 3.23.0 M3
  examples/org.eclipse.rap.demo.controls/launch/RAP Controls Demo.launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Business).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Fancy).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (OSGi).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo.launch
  examples/org.eclipse.rap.examples/launch/RAP Examples Demo.launch
  features/org.eclipse.rap.e4.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.equinox.target.feature/feature.xml
  features/org.eclipse.rap.e4.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.sdk.feature/.forceQualifierUpdate
  features/org.eclipse.rap.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.equinox.target.feature/feature.xml
  features/org.eclipse.rap.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.feature/.forceQualifierUpdate
  features/org.eclipse.rap.sdk.feature/.forceQualifierUpdate
  releng/org.eclipse.rap.build/pom.xml
  releng/org.eclipse.rap.examples.build/controlsdemo/assembly.xml
  releng/org.eclipse.rap.examples.build/controlsdemo/pom.xml
  releng/org.eclipse.rap.examples.build/rapdemo/assembly.xml
  releng/org.eclipse.rap.examples.build/rapdemo/pom.xml
  releng/org.eclipse.rap.examples.build/workbenchdemo/assembly.xml
  releng/org.eclipse.rap.examples.build/workbenchdemo/pom.xml
  tests/org.eclipse.rap.rwt.jstest/RWT Client Tests.launch
Labels: releng

#78 Fix item height with auto-height enabled on Grid creation
  bundles/org.eclipse.rap.rwt/js/rwt/widgets/Grid.js
  tests/org.eclipse.rap.rwt.jstest/RWT Client Tests.launch
Labels: bug

#80 Synchronise SLF4J plugin to Eclipse Platform
  examples/org.eclipse.rap.demo.controls/launch/RAP Controls Demo.launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Business).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Fancy).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (OSGi).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo.launch
  examples/org.eclipse.rap.examples/launch/RAP Examples Demo.launch
  features/org.eclipse.rap.e4.equinox.target.feature/feature.xml
  features/org.eclipse.rap.equinox.target.feature/feature.xml
  tests/org.eclipse.rap.rwt.jstest/RWT Client Tests.launch
Labels: releng

#81 Automatically include all dependencies in output p2 repositories
  releng/org.eclipse.rap.build/repository.e4/pom.xml
  releng/org.eclipse.rap.build/repository/pom.xml
Labels: releng

#82 Add "slf4j.nop" bundle to all demo launch configurations
  examples/org.eclipse.rap.demo.controls/launch/RAP Controls Demo.launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Business).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Fancy).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (OSGi).launch
  examples/org.eclipse.rap.demo/launch/RAP Workbench Demo.launch
  examples/org.eclipse.rap.examples/launch/RAP Examples Demo.launch
Labels: releng

#89 Update build configuration for RAP Runtime 3.23.0 RC2
  features/org.eclipse.rap.e4.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.sdk.feature/.forceQualifierUpdate
  features/org.eclipse.rap.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.feature/.forceQualifierUpdate
  features/org.eclipse.rap.sdk.feature/.forceQualifierUpdate
  releng/org.eclipse.rap.build/pom.xml
Labels: releng
