Repository eclipse-rap/org.eclipse.rap, pull requests merged in 2023-01, with the labels that each got.

#97 Update build configuration for RAP Runtime 3.24.0 M1
  features/org.eclipse.rap.e4.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.sdk.feature/.forceQualifierUpdate
  features/org.eclipse.rap.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.feature/.forceQualifierUpdate
  features/org.eclipse.rap.sdk.feature/.forceQualifierUpdate
  releng/org.eclipse.rap.build/pom.xml
Labels: releng

#100 Improve connection error handling when fetch is used
  bundles/org.eclipse.rap.rwt/js/rwt/remote/Request.js
Labels: bug, enhancement

#103 Fix error handling connection retry button with CSP applied
  bundles/org.eclipse.rap.rwt/js/rwt/runtime/ErrorHandler.js
Labels: bug

#105 Improve connection "retry" behavior in ErrorHandle.js
  bundles/org.eclipse.rap.rwt/js/rwt/runtime/ErrorHandler.js
Labels: enhancement
