Repository eclipse-rap/org.eclipse.rap, pull requests merged in 2024-08, with the labels that each got.

#213 Remove unused imports from MANIFEST.MF
  tests/org.eclipse.rap.fileupload.test/META-INF/MANIFEST.MF
Labels: releng

#214 Don't hide shared controls in CTabFolder
  bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/custom/CTabFolder.java
  tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/custom/CTabFolder_Test.java
Labels: bug

#215 Add 'insertText' method to the Nebula RichTextEditor
  bundles/org.eclipse.rap.nebula.widgets.richtext/src/org/eclipse/nebula/widgets/richtext/RichTextEditor.java
  bundles/org.eclipse.rap.nebula.widgets.richtext/src/resources/RichTextEditor.js
  bundles/org.eclipse.rap.nebula.widgets.richtext/src/resources/RichTextEditorHandler.js
  examples/org.eclipse.rap.demo.controls/src/org/eclipse/rap/demo/controls/NebulaRichTextTab.java
Labels: enhancement

#216 Disable ok button immediately to avoid "Widget disposed" error
  bundles/org.eclipse.rap.filedialog/src/org/eclipse/swt/widgets/FileDialog.java
Labels: bug

#190 Fix Grid getColumn calculation when row header is visible
  bundles/org.eclipse.rap.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
Labels: bug

#219 Update build configuration for RAP Runtime 4.0.0 M3
  features/org.eclipse.rap.e4.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.sdk.feature/.forceQualifierUpdate
  features/org.eclipse.rap.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.feature/.forceQualifierUpdate
  features/org.eclipse.rap.sdk.feature/.forceQualifierUpdate
  releng/org.eclipse.rap.build/pom.xml
Labels: releng

#191 Export all packages from org.eclipse.rap.nebula.jface.gridviewer
  bundles/org.eclipse.rap.nebula.jface.gridviewer/META-INF/MANIFEST.MF
Labels: enhancement

#221 Update build configuration for RAP Runtime 4.0.0 RC1
  features/org.eclipse.rap.e4.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.feature/.forceQualifierUpdate
  features/org.eclipse.rap.e4.sdk.feature/.forceQualifierUpdate
  features/org.eclipse.rap.equinox.target.feature/.forceQualifierUpdate
  features/org.eclipse.rap.examples.feature/.forceQualifierUpdate
  features/org.eclipse.rap.feature/.forceQualifierUpdate
  features/org.eclipse.rap.sdk.feature/.forceQualifierUpdate
  releng/org.eclipse.rap.build/pom.xml
Labels: releng

#225 Use correct extension point names in Java code
  bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/FilterManager.java
  bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/HttpContextManager.java
  bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/ResourceManager.java
  bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/ServletManager.java
Labels: bug
